// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reflecta.Data.Data;

#nullable disable

namespace Reflecta.Data.Data.Migrations
{
    [DbContext(typeof(ReflectaDbContext))]
    partial class ReflectaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Reflecta.Data.Models.EntrySecondaryMood", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<int>("MoodId")
                        .HasColumnType("integer")
                        .HasColumnName("mood_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("EntryId", "MoodId");

                    b.HasIndex("MoodId");

                    b.ToTable("entry_secondary_moods");
                });

            modelBuilder.Entity("Reflecta.Data.Models.EntryTag", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("EntryId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("entry_tags");
                });

            modelBuilder.Entity("Reflecta.Data.Models.ExportLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DateRangeEnd")
                        .HasColumnType("date")
                        .HasColumnName("date_range_end");

                    b.Property<DateOnly>("DateRangeStart")
                        .HasColumnType("date")
                        .HasColumnName("date_range_start");

                    b.Property<int>("EntriesCount")
                        .HasColumnType("integer")
                        .HasColumnName("entries_count");

                    b.Property<string>("ExportFormat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("export_format");

                    b.Property<DateTime>("ExportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exported_at");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("export_logs");
                });

            modelBuilder.Entity("Reflecta.Data.Models.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_favorite");

                    b.Property<int>("PrimaryMoodId")
                        .HasColumnType("integer")
                        .HasColumnName("primary_mood_id");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer")
                        .HasColumnName("word_count");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryMoodId");

                    b.HasIndex("UserId", "EntryDate")
                        .IsUnique();

                    b.ToTable("journal_entries");
                });

            modelBuilder.Entity("Reflecta.Data.Models.Mood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("emoji");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("moods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Positive",
                            DisplayOrder = 1,
                            Emoji = "😊",
                            IsActive = true,
                            Name = "Happy"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Positive",
                            DisplayOrder = 2,
                            Emoji = "🤩",
                            IsActive = true,
                            Name = "Excited"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Positive",
                            DisplayOrder = 3,
                            Emoji = "🙏",
                            IsActive = true,
                            Name = "Grateful"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Positive",
                            DisplayOrder = 4,
                            Emoji = "😌",
                            IsActive = true,
                            Name = "Calm"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Positive",
                            DisplayOrder = 5,
                            Emoji = "🥰",
                            IsActive = true,
                            Name = "Loved"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Positive",
                            DisplayOrder = 6,
                            Emoji = "💪",
                            IsActive = true,
                            Name = "Proud"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Neutral",
                            DisplayOrder = 7,
                            Emoji = "😐",
                            IsActive = true,
                            Name = "Okay"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Neutral",
                            DisplayOrder = 8,
                            Emoji = "😴",
                            IsActive = true,
                            Name = "Tired"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Neutral",
                            DisplayOrder = 9,
                            Emoji = "🤔",
                            IsActive = true,
                            Name = "Thinking"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Neutral",
                            DisplayOrder = 10,
                            Emoji = "😑",
                            IsActive = true,
                            Name = "Bored"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Negative",
                            DisplayOrder = 11,
                            Emoji = "😢",
                            IsActive = true,
                            Name = "Sad"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Negative",
                            DisplayOrder = 12,
                            Emoji = "😰",
                            IsActive = true,
                            Name = "Anxious"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Negative",
                            DisplayOrder = 13,
                            Emoji = "😠",
                            IsActive = true,
                            Name = "Angry"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Negative",
                            DisplayOrder = 14,
                            Emoji = "😫",
                            IsActive = true,
                            Name = "Stressed"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Negative",
                            DisplayOrder = 15,
                            Emoji = "😔",
                            IsActive = true,
                            Name = "Lonely"
                        });
                });

            modelBuilder.Entity("Reflecta.Data.Models.Streak", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer")
                        .HasColumnName("current_streak");

                    b.Property<DateOnly?>("LastEntryDate")
                        .HasColumnType("date")
                        .HasColumnName("last_entry_date");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("integer")
                        .HasColumnName("longest_streak");

                    b.Property<DateOnly?>("StreakStartDate")
                        .HasColumnType("date")
                        .HasColumnName("streak_start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("streaks");
                });

            modelBuilder.Entity("Reflecta.Data.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Name", "UserId")
                        .IsUnique();

                    b.ToTable("tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "#4A90D9",
                            CreatedAt = new DateTime(2026, 1, 26, 16, 4, 17, 29, DateTimeKind.Utc).AddTicks(4810),
                            IsActive = true,
                            IsSystem = true,
                            Name = "Work"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Color = "#7ED321",
                            CreatedAt = new DateTime(2026, 1, 26, 16, 4, 17, 29, DateTimeKind.Utc).AddTicks(5350),
                            IsActive = true,
                            IsSystem = true,
                            Name = "Personal"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Color = "#F5A623",
                            CreatedAt = new DateTime(2026, 1, 26, 16, 4, 17, 29, DateTimeKind.Utc).AddTicks(5360),
                            IsActive = true,
                            IsSystem = true,
                            Name = "Health"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Color = "#D0021B",
                            CreatedAt = new DateTime(2026, 1, 26, 16, 4, 17, 29, DateTimeKind.Utc).AddTicks(5360),
                            IsActive = true,
                            IsSystem = true,
                            Name = "Family"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Color = "#9013FE",
                            CreatedAt = new DateTime(2026, 1, 26, 16, 4, 17, 29, DateTimeKind.Utc).AddTicks(5370),
                            IsActive = true,
                            IsSystem = true,
                            Name = "Travel"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Color = "#50E3C2",
                            CreatedAt = new DateTime(2026, 1, 26, 16, 4, 17, 29, DateTimeKind.Utc).AddTicks(5420),
                            IsActive = true,
                            IsSystem = true,
                            Name = "Goals"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Color = "#BD10E0",
                            CreatedAt = new DateTime(2026, 1, 26, 16, 4, 17, 29, DateTimeKind.Utc).AddTicks(5420),
                            IsActive = true,
                            IsSystem = true,
                            Name = "Learning"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Color = "#FF6B6B",
                            CreatedAt = new DateTime(2026, 1, 26, 16, 4, 17, 29, DateTimeKind.Utc).AddTicks(5430),
                            IsActive = true,
                            IsSystem = true,
                            Name = "Relationships"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Color = "#4ECDC4",
                            CreatedAt = new DateTime(2026, 1, 26, 16, 4, 17, 29, DateTimeKind.Utc).AddTicks(5430),
                            IsActive = true,
                            IsSystem = true,
                            Name = "Mindfulness"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Color = "#FFE66D",
                            CreatedAt = new DateTime(2026, 1, 26, 16, 4, 17, 29, DateTimeKind.Utc).AddTicks(5430),
                            IsActive = true,
                            IsSystem = true,
                            Name = "Creativity"
                        });
                });

            modelBuilder.Entity("Reflecta.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Reflecta.Data.Models.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("PinEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("pin_enabled");

                    b.Property<string>("PinHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pin_hash");

                    b.Property<bool>("ReminderEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("reminder_enabled");

                    b.Property<TimeOnly?>("ReminderTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("reminder_time");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("theme");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_settings");
                });

            modelBuilder.Entity("Reflecta.Data.Models.EntrySecondaryMood", b =>
                {
                    b.HasOne("Reflecta.Data.Models.JournalEntry", "Entry")
                        .WithMany("SecondaryMoods")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reflecta.Data.Models.Mood", "Mood")
                        .WithMany("SecondaryMoodEntries")
                        .HasForeignKey("MoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Mood");
                });

            modelBuilder.Entity("Reflecta.Data.Models.EntryTag", b =>
                {
                    b.HasOne("Reflecta.Data.Models.JournalEntry", "Entry")
                        .WithMany("EntryTags")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reflecta.Data.Models.Tag", "Tag")
                        .WithMany("EntryTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Reflecta.Data.Models.ExportLog", b =>
                {
                    b.HasOne("Reflecta.Data.Models.User", "User")
                        .WithMany("ExportLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Reflecta.Data.Models.JournalEntry", b =>
                {
                    b.HasOne("Reflecta.Data.Models.Mood", "PrimaryMood")
                        .WithMany("PrimaryMoodEntries")
                        .HasForeignKey("PrimaryMoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reflecta.Data.Models.User", "User")
                        .WithMany("JournalEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryMood");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Reflecta.Data.Models.Streak", b =>
                {
                    b.HasOne("Reflecta.Data.Models.User", "User")
                        .WithOne("Streak")
                        .HasForeignKey("Reflecta.Data.Models.Streak", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Reflecta.Data.Models.Tag", b =>
                {
                    b.HasOne("Reflecta.Data.Models.User", "User")
                        .WithMany("CustomTags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Reflecta.Data.Models.UserSettings", b =>
                {
                    b.HasOne("Reflecta.Data.Models.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("Reflecta.Data.Models.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Reflecta.Data.Models.JournalEntry", b =>
                {
                    b.Navigation("EntryTags");

                    b.Navigation("SecondaryMoods");
                });

            modelBuilder.Entity("Reflecta.Data.Models.Mood", b =>
                {
                    b.Navigation("PrimaryMoodEntries");

                    b.Navigation("SecondaryMoodEntries");
                });

            modelBuilder.Entity("Reflecta.Data.Models.Tag", b =>
                {
                    b.Navigation("EntryTags");
                });

            modelBuilder.Entity("Reflecta.Data.Models.User", b =>
                {
                    b.Navigation("CustomTags");

                    b.Navigation("ExportLogs");

                    b.Navigation("JournalEntries");

                    b.Navigation("Settings");

                    b.Navigation("Streak");
                });
#pragma warning restore 612, 618
        }
    }
}
